set nocompatible              " be iMproved, required
filetype off                  " required


" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'
nmap <silent><F3> :NERDTreeToggle<CR>
Plugin 'kien/ctrlp.vim'
Plugin 'rust-lang/rust.vim'
"Plugin 'fs111/pydoc.vim'
"Plugin 'pangloss/vim-javascript'
Plugin 'sheerun/vim-polyglot'
Plugin 'Shougo/neocomplete.vim'
	"Note: This option must be set in .vimrc(_vimrc).  NOT IN
	".gvimrc(_gvimrc)!
	"" Disable AutoComplPop.
	let g:acp_enableAtStartup = 0
	" Use neocomplete.
	let g:neocomplete#enable_at_startup = 1
	" Use smartcase.
	let g:neocomplete#enable_smart_case = 1
	" Set minimum syntax keyword length.
	let g:neocomplete#sources#syntax#min_keyword_length = 3

	let g:neocomplete#data_diretory = $HOME.'/.vim/tmp/neocomplete'

	" Define dictionary.
	let g:neocomplete#sources#dictionary#dictionaries = {
				\ 'default' : '',
				\ 'vimshell' : $HOME.'/.vim/tmp/vimshell_hist',
				\ 'scheme' : $HOME.'/.vim/tmp/gosh_completions'
				\ }

	" Define keyword.
	if !exists('g:neocomplete#keyword_patterns')
		let g:neocomplete#keyword_patterns = {}
	endif
	let g:neocomplete#keyword_patterns['default'] = '\h\w*'
	noremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"	

	autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
	autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
	autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
	autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
	autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

	" Enable heavy omni completion.
	if !exists('g:neocomplete#sources#omni#input_patterns')
		let g:neocomplete#sources#omni#input_patterns = {}
	endif
" Plugin 'Valloric/YouCompleteMe'

call vundle#end()            " required
filetype plugin indent on    " required
" ------------------------------------------------
" ------------------------------------------------
" ------------------------------------------------

if has("syntax")
  syntax on
endif

set viminfo='10,\"100,:20,%,n~/.vim/tmp/viminfo
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nu
" set foldmethod=syntax
" set foldlevel=99
"set hlsearch
set t_Co=256
"set backspace=2
"set bg=dark
set wrap
set encoding=utf8
set fileencoding=utf8
set fileencodings=utf8,gbk,gb2321

"status line 
"-----------------------------------
set showcmd
set showmode
set ruler

set laststatus=2
set statusline=%t\ [%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y
set statusline+=%=
set statusline+=\ %c,%l/%L\ \|\ %n\ \|\ %P
"-----------------------------------

if has('gui_running')
    set guioptions-=T  " no toolbar
    colorscheme codeschool
else
    colorscheme pablo
endif
