#!/bin/sh
if [ -f $HOME/.config/Xresources ]; then
    xrdb $HOME/.config/Xresources
fi

if [ -f $HOME/.config/Xmodmap ]; then
    xmodmap $HOME/.config/Xmodmap
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/* ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# env setting
export LC_ALL=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN.UTF-8
# input method
export LC_CTYPE=zh_CN.UTF-8
export XIM="fcitx"
export XIM_PROGRAM="fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
export XMODIFIERS="@im=fcitx"

exec awesome 
